# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: AyushChothe.DockerRemote
PackageVersion: 0.3.1.6
Installers:
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.17763.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://github.com/AyushChothe/docker_remote/releases/download/Release_0.3.1.6/docker_remote_0.3.1.6.msix
  InstallerSha256: 5B6154174F506B851D5AC4F9BBE0525ECB7C0E822B657508A35670B1DF3455D1
  SignatureSha256: 2762D092050B7AC13973D86870F6E08C4D20032E34DAAC73BB4A35A5F44D262B
  PackageFamilyName: com.ashtech.docker-remote_wm9xvt1g9vkee
ManifestType: installer
ManifestVersion: 1.2.0

